version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"
    restart: always
    environment:
      NODE_ENV: development
      DATABASE_TYPE: postgres
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://cache
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000
      ADMIN_CORS: https://admin-medusa.lamvieconha.com
      STORE_CORS: https://medusa.lamvieconha.com
    volumes:
      - backend_static:/app/medusa/static
    networks:
      - bridged

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    networks:
      - bridged

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    ports:
      - "6379:6379"
    restart: always
    networks:
      - bridged

  admin:
    container_name: medusa-front-admin
    build:
      context: ./admin
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    ports:
      - "7000:80"
      # - "7000:7000"
      # - "7001:7001"
    environment:
      # NODE_ENV: development
      NODE_ENV: production
      NODE_OPTIONS: --openssl-legacy-provider
      REDIS_URL: redis://cache
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
    networks:
      - bridged

  storefront:
    container_name: medusa-front-store
    build:
      context: ./storefront
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    ports:
      - "8000:8000"
      # - "8000:80"
    environment:
      NODE_ENV: development
      # NODE_ENV: production
      # NEXT_PUBLIC_STRIPE_KEY: 
      # NEXT_PUBLIC_PAYPAL_CLIENT_ID: 
      # NEXT_PUBLIC_SEARCH_APP_ID: 
      # NEXT_PUBLIC_SEARCH_ENDPOINT: http://127.0.0.1:7700
      # NEXT_PUBLIC_SEARCH_API_KEY: 
      # NEXT_PUBLIC_SEARCH_INDEX_NAME: products
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: https://backend-medusa.lamvieconha.com
      MEDUSA_BACKEND_URL: https://backend-medusa.lamvieconha.com
      PORT: 8000
    networks:
      - bridged

  proxy:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - bridged
    # network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.1"
    # depends_on:
      # - ypay-noti-worker
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]
    

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw

networks:
  bridged:
    driver: bridge

volumes:
  storefront_node_modules:
  backend_node_modules:
  backend_static: